[features]
seeds = false
skip-lint = false

[programs.localnet]
wnft = "wnftDJ4FRB46dVCPSkPejyCxuyhcCrVirnAAC4k757B"
wnft-collection = "wnfcodchjmiS96bd9pKCoUBir6V2C6ucGXWYCWHMXuF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aankor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 2000000 tests/**/*.ts"
